name: Release transmission-daemon workflow

on:
  push:
    tags:
      - 'transmission-daemon*'

jobs:
  build-transmission-daemon:
    strategy:
      matrix:
        arch: [amd64, arm64]
    uses: ./.github/workflows/build_transmission-daemon_base_workflow.yml
    with:
      arch: ${{ matrix.arch }}

  release-transmission-daemon:
    runs-on: ubuntu-latest
    needs: [build-transmission-daemon]
    strategy:
      matrix:
        arch: [amd64, arm64]
    env:
      TRANSMISSION_VERSION: 4.0.5
    steps:
      # Checkout the repository, this is needed for 'gh' to work
      - uses: actions/checkout@v4.1.6

      - name: Download transmission-daemon release files
        uses: actions/download-artifact@v4.1.7
        with:
          name: transmission-daemon-${{ env.TRANSMISSION_VERSION }}-${{ matrix.arch }}.tar.xz

      - name: Create Transmission Daemon Release
        id: create_release
        run: |
          tag_name=$(echo "${GITHUB_REF#refs/tags/}")
          body="Release notes for $tag_name"

          echo "Creating release $tag_name"
          gh release create "$tag_name" "out/transmission-daemon-${{ env.TRANSMISSION_VERSION }}-${{ matrix.arch }}.tar.xz" --notes "$body"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Release
        run: |
          release_id=$(gh release view "$tag_name" --json id -q ".id")
          echo "Release ID: $release_id"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
